site_name: nebulaplugins-aws
site_url: https://kozmoai.github.io/nebulaplugins-aws
repo_url: https://github.com/kozmoai/nebulaplugins-aws
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: docs/overrides
  favicon: img/favicon.ico
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
          icon: material/brightness-auto
          name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      accent: blue
      primary: blue
      scheme: default
      toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      accent: blue
      primary: blue
      scheme: slate
      toggle:
          icon: material/weather-night
          name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  logo:
    img/nebula-logo-mark.png
  font:
    text: Inter
    code: Source Code Pro
  features:
    - content.code.copy
    - content.code.annotate
extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed
    - pymdownx.inlinehilite
    - pymdownx.snippets

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_examples_catalog.py
        - docs/gen_blocks_catalog.py
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: True
            show_object_full_path: False
            show_category_heading: True
            show_bases: True
            show_signature: False
            heading_level: 1
watch:
  - nebula_aws/
  - README.md

nav:
    - Home: index.md
    - ECS Worker Guide: ecs_guide.md
    - Blocks Catalog: blocks_catalog.md
    - Examples Catalog: examples_catalog.md
    - Contributing: contributing.md
    - API Reference:
        - Batch: batch.md
        - Client Waiter: client_waiter.md
        - Credentials: credentials.md
        - ECS Worker: ecs_worker.md
        - ECS: ecs.md
        - Lambda: lambda_function.md
        - Deployments:
          - Steps: deployments/steps.md
        - S3: s3.md
        - Secrets Manager: secrets_manager.md

extra:
    social:
        - icon: fontawesome/brands/slack
          link: https://www.nebula.io/slack/
        - icon: fontawesome/brands/discourse
          link: https://discourse.nebula.io/
        - icon: fontawesome/brands/youtube
          link: https://www.youtube.com/c/NebulaIO/videos
        - icon: fontawesome/regular/newspaper
          link: https://nebula.io/guide/
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/NebulaIO
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/nebula/
        - icon: fontawesome/brands/github
          link: https://github.com/kozmoai/nebula
        - icon: fontawesome/brands/docker
          link: https://hub.docker.com/r/kozmoai/nebula/
        - icon: fontawesome/brands/python
          link: https://pypi.org/project/nebula/
    analytics:
        provider: custom
        property: G-8CSMBCQDKN